pool:
  vmImage: $(Build.VmImage)

schedules:
  - cron: "0 */1 * * *"
    displayName: "Build every hour"
    branches:
      include:
      - master
    always: true

steps:
- checkout: none

- bash: docker pull $(Build.DockerImage)
  displayName: docker pull $(Build.DockerImage)
