pool:
  vmImage: windows-2019

schedules:
  - cron: "0 */1 * * *"
    displayName: "Build every hour"
    branches:
      include:
      - master
    always: true

steps:
- bash: docker-compose pull
  displayName: docker-compose pull
